### ISSUE TITLE
Cannot find .h files in Pods

### ISSUE THREAD

**Issue by pranavkundra** [GoogleCloudPlatform/ios-docs-samples#3] opened 2016-04-30 13:46 UTC
When I try to run the Streaming gRPC Objective-C Sample (after Pod install and replacing API key), I get the following build error:

openssl/asn1.h file not found

However, in the Pods project, under BoringSSL, I can see the file asn1.h defined. Clicking on 'Open in Finder' takes me to the location of the file (meaning that XCode is able to find the file).

Please advise.

**Comment by timburks** [comment] 2016-05-13 19:59
We've seen some problems like this when the use_frameworks! directive is enabled in Podfiles. Unfortunately the problem is in the gRPC Cocoapods configuration (frameworks are not built correctly), but a solution for that is in progress.

**Comment by adil-appifytech** [comment] 2016-06-21 10:34
@timburks - Just wondering if sol has been pushed?

**Comment by timburks** [comment] 2016-06-23 15:29
Not yet. The changes are in https://github.com/jcanizales/grpc/tree/support-dynamic-frameworks and work for simpler examples (like the [stickynote api](https://github.com/GoogleCloudPlatform/ios-docs-samples/tree/master/solutions/stickynoteapi/gRPC) sample) but there's one more problem remaining with hierarchical pathnames in the code generated by the protoc plugin. @jcanizales is working on that now.

**Comment by adil-appifytech** [comment] 2016-06-24 06:29
@timburks - Thanks for the reply. I have fixed the issue by moving my swift libraries to be included via Carthage and don't use use_framework!. Just in case anyone wants to know how to make it work in Swift Projects.

**Comment by timburks** [comment] 2016-07-24 21:03
This is fixed in the latest samples, which are using a prerelease of grpc 1.0.0 for Objective-C. https://github.com/GoogleCloudPlatform/ios-docs-samples/commit/3c3681e5435e66fabb2513c2104a33b375351784

**Closed by timburks** 2016-07-24 21:03 UTC

**Comment by gerchicov-bp** [comment] 2017-12-22 13:15
@timburks it is not fixed in swift example and is not fixed for both objective-c and swift when you try to import with cocoapods
